### ISSUE TITLE
Update tutorials in traits/ to use API 

### ISSUE THREAD

**Issue by dlebauer** [terraref/tutorials#1]
@infotroph here are some use cases - it might be a good way to guide your development on the traits package to go through and get these functions to work. Some of them started with .csv files, others with a direct database connection ...

I am going to present these next week so will be working on preparing them.

**Comment by infotroph** [comment]
I'll be working on this after 10:30 CST today. To be clear, you want to convert these tutorials so they consistently use the API, including the ones that are currently sourced from CSV or local database, yes?

**Comment by dlebauer** [comment]
That is correct. Feel free to augment with additional exploratory plots / descriptive statistics. Look through all first and note that 3,4 need the most work. Number 1 might not work b/c server timeout due to 16 million rows of simulated data. I'm re-indexing but it is slow and I may end up reducing the amount of data.

**Comment by infotroph** [comment]
Have done most of a first pass but gotta catch a bus. Will push as soon as I get network again

**Comment by infotroph** [comment]
Looks like I don't have permission to either push or fork, and I'll be mostly offline Sat and Sun. On the I've posted a rewritten version of the agronomic metadata demo at https://gist.github.com/infotroph/45587225b93544d44dbf8c65fd4ed5cb in case you need it before then.
