### ISSUE TITLE
Review updated methods 

### ISSUE THREAD

**Issue by kimberlyh66** [terraref/tutorials#106]
Please review new methods defined in the spreadsheet https://docs.google.com/spreadsheets/d/1Pk_k5zm1W7I1jhzKoxMSGBhrHAPBWZh5GF2PL2vWrfk/edit#gid=112857053

**Comment by kimberlyh66** [comment]
For records highlighted in yellow, check if suggested existing method should be associated with trait.

**Comment by kimberlyh66** [comment]
@dlebauer I have finished updating the methods. Please review at https://docs.google.com/spreadsheets/d/1Pk_k5zm1W7I1jhzKoxMSGBhrHAPBWZh5GF2PL2vWrfk/edit#gid=112857053. 

Can you highlight the methods that you revise so I can make changes to associated SQL statements? I will run the SQL statements against the test database after receiving your feedback.

**Comment by dlebauer** [comment]
Initial feedback after looking at a few methods ... are you linking these new methods with citations that point to methods in protocols.io where they exist?

**Comment by Chris-Schnaufer** [comment]
Kimberly and David to discuss review
