### ISSUE TITLE
Don't overwrite variables in vignettes/04-synthesis-data.Rmd

### ISSUE THREAD

**Issue by Chris-Schnaufer** [terraref/tutorials#111]
This didn't make it into [Hadley's style guide](http://adv-r.had.co.nz/Style.html) but I think it is a good idea to avoid overwriting objects, mostly because overwriting an object can lead to errors that are difficult to debug in interactive use.

Here you could just pipe the result of the query to the mutate function. In other cases (unless the object is v. big) you can increment the object name. I think that when the object is very big, it is okay to break the rule.

**Comment by Chris-Schnaufer** [comment]
Review if this has been done

**Comment by KristinaRiemer** [comment]
See #119
