### ISSUE TITLE
Update methods for deploying terraref / bety instance locally w/ docker

### ISSUE THREAD

**Issue by dlebauer** [terraref/tutorials#116]
David - find commands sent by Rob, review, post, and discuss how to make it easier

**Comment by dlebauer** [comment]
These are notes that I have from @robkooper ...

```sh
git clone git@github.com:pecanproject/bety
cd bety

# mount postgres container to port 5432 in docker-compose.override file
wget https://gist.githubusercontent.com/dlebauer/a2cd7fec09280e5a01e208e91806694f/raw/7fd122055c1c7995ac2d606ec67b25402d2ae9de/docker-compose.override.yml

# start postgres
docker-compose up -p bety -d postgres 
   # not sure why that isn't working!

# initialize BETY database
docker run -ti --rm --network bety_bety -e BETY_INITIALIZE_URL='-w https://terraref.ncsa.illinois.edu/bety/dump/bety0/bety.tar.gz' pecan/bety:terra initialize

# sync with server 6 only
docker run -ti --rm --network bety_bety -e REMOTE_SERVERS='6' pecan/bety:terra sync

# bring up full stack
docker-compose up

# log into database
psql -h localhost -U bety
```

**Comment by dlebauer** [comment]
@kimberlyh66 could you see if this works, and ask Chris or Rob for help if (or when ... I wasn't able to get past compose) you run into trouble?

**Comment by kimberlyh66** [comment]
@dlebauer Chris helped me get the compose step working. The commands were in the wrong order. The correct way is `docker-compose -p bety up -d postgres`.

**Comment by kimberlyh66** [comment]
Updated notes on how to deploy terraref/bety instance with docker (only change made from above is the docker compose step to start up postgres):

git clone git@github.com:pecanproject/bety
cd bety

# mount postgres container to port 5432 in docker-compose.override file
wget https://gist.githubusercontent.com/dlebauer/a2cd7fec09280e5a01e208e91806694f/raw/7fd122055c1c7995ac2d606ec67b25402d2ae9de/docker-compose.override.yml

# start postgres
docker-compose -p bety up -d postgres

# initialize BETY database
docker run -ti --rm --network bety_bety -e BETY_INITIALIZE_URL='-w https://terraref.ncsa.illinois.edu/bety/dump/bety0/bety.tar.gz' pecan/bety:terra initialize

# sync with server 6 only
docker run -ti --rm --network bety_bety -e REMOTE_SERVERS='6' pecan/bety:terra sync

# bring up full stack
docker-compose up

# log into database
psql -h localhost -U bety

**Comment by dlebauer** [comment]
This can be added to our group wiki page, though I am not sure if the best place for the docker-compose.override.yml file is as a gist, or if there is a repository that it should be in.
