### ISSUE TITLE
Update trait-weather models in synthesis vignette once trait data is updated

### ISSUE THREAD

**Issue by KristinaRiemer** [terraref/tutorials#121]

**Comment by KristinaRiemer** [comment]
Data is apparently still not ready.

**Comment by KristinaRiemer** [comment]
Trait data appears to still not be updated.

**Comment by dlebauer** [comment]
Did you try Season 6 / 2018 canopy cover? It should be available.

**Comment by KristinaRiemer** [comment]
When I ran lines 29-34 from your first commit from https://github.com/terraref/tutorials/pull/149/commits/95b42c94c95560667c1edc6b051aef7f94c2fa46, there was canopy cover data from May, June, and July, but there was no corresponding weather data for those dates. It's the same when pulling data from season 6 instead of using the year. 🤷‍♀
