### ISSUE TITLE
Functions for metadata upload

### ISSUE THREAD

**Issue by kimberlyh66** [terraref/tutorials#129]
Define for each function:
* name
* inputs
* output
* purpose

**Comment by kimberlyh66** [comment]
1. name: **constraint_check**

    purpose: 

    * check if user provided metadata violates any table constraints (experiment name, site name, and specie id / cultivar combination must be unique)

    * stops `upload_metadata` (described below) from running if a constraint is violated

    inputs: database connection, experiment name, site names, specie id / cultivar combos

    output: 0 (constraint violation), 1 (no constraint violation)

2. name: **format_check** 

    purpose: 
    * check if user provided metadata is in correct format

    * stops `upload_metadata` (described below) from running if a format error is found

    inputs: all metadata

    output: 0 (format error), 1 (no format error)

3. name: **upload_metadata**

    purpose: 

    * uploads metadata step by step (see documentation of steps at #125)

    * calls the `constraint_check` and `format_check` functions

    * stops running if `0` is returned by `constraint_check` or `format_check`; displays error message

    * calls the `add_(tableName)` and `associate_(tblName1)_(tblName2)` functions described below if format and constraint checks are successful 

    inputs: database connection, all metadata

    output:  success or error message (an error message is outputted by stop)

4. name: **add_experiment**

    purpose: insert a new row into the `experiments` table

    inputs: database connection, experiment metadata

    output: message

5. name: **add_site**

    purpose: insert a new row into the `sites` table

    inputs: database connection, site metadata

    output: message

6. name: **add_cultivar**

    purpose: insert a new row into the `cultivars` table

    inputs: database connection, cultivar metadata

    output: message

7. name: **add_treatment**

    purpose: insert a new row into the `treatments` table

    inputs: database connection, treatment metadata

    output: message

8. name: **add_citation**

    purpose: insert a new row into the `citations` table

    inputs: database connection, citation metadata

    output: message

9. name: **associate_exp_sites**

    purpose: insert new rows into the `experiments_sites` table

    inputs: database connection, experiment id, site ids

    output: message

10. name: **associate_exp_treat**

    purpose: insert new rows into the `experiments_treatments` table

    inputs: database connection, experiment id, treatment id

    output: message

11. name: **associate_cite_sites**

    purpose: insert new rows into the `citations_sites` table

    inputs: database connection, citation id, site ids

    output: message

**Comment by dlebauer** [comment]
This is done, we can review in a high level architecture meeting next week
