### ISSUE TITLE
Create first version of metadata upload package

### ISSUE THREAD

**Issue by kimberlyh66** [terraref/tutorials#141]
In addition to functions required for metadata upload, package should also include betydb functions from ropensci traits.

**Comment by Chris-Schnaufer** [comment]
Kristina reviews

**Comment by kimberlyh66** [comment]
See [https://github.com/kimberlyh66/betydbtools](https://github.com/kimberlyh66/betydbtools) for details

**Comment by kimberlyh66** [comment]
Kristina reviews pull request https://github.com/az-digitalag/betydbtools/pull/1

**Comment by kimberlyh66** [comment]
Updated pull request: https://github.com/az-digitalag/betydbtools/pull/2

**Comment by dlebauer** [comment]
PR Merged. Functionality has been implemented in BETYdb-YABA
