### ISSUE TITLE
Add radio button for displaying heat map

### ISSUE THREAD

**Issue by kimberlyh66** [terraref/tutorials#152]
* Radio button should be displayed next to scan selector

* Value should determine whether heat map is displayed on top of full field image

**Comment by kimberlyh66** [comment]
Added Yes/No radio buttons to allow user to choose whether to display heat map.

Changes made in `heat-map-updates` branch of [forked repository](https://github.com/kimberlyh66/traitvis-webapp).

**Comment by Chris-Schnaufer** [comment]
Need to make a pull request

**Comment by kimberlyh66** [comment]
Updated to a single toggle button. See pull request: https://github.com/terraref/traitvis-webapp/pull/27. Also tied to #153.

**Comment by dlebauer** [comment]
closed by https://github.com/terraref/traitvis-webapp/pull/27
