### ISSUE TITLE
Speed up rendering of heat map 

### ISSUE THREAD

**Issue by kimberlyh66** [terraref/tutorials#153]
* for loop to add trait value polygons to leaflet map is taking too long

**Comment by kimberlyh66** [comment]
There does not seem to be a way to add multiple polygons to leaflet map at once. Seems like a for loop must be used to continuously add new polygons to map.

**Comment by dlebauer** [comment]
There is also a datatype called 'multipolygon'. Can you see if leaflet will handle these, and if so coerce the data to a multipolygon (maybe something like [sf::st_cast](https://r-spatial.github.io/sf/reference/st_cast.html)?

**Comment by kimberlyh66** [comment]
@dlebauer Good suggestion. Looks like the `mapview` package has a function that can be used to add a multipolygon to leaflet map.

**Comment by kimberlyh66** [comment]
Changes made in `heat-map-updates` branch of [forked repository](https://github.com/kimberlyh66/traitvis-webapp)

**Comment by Chris-Schnaufer** [comment]
Kimberly to make a pull request for David to review

**Comment by Chris-Schnaufer** [comment]
Also tied in to #152

**Comment by kimberlyh66** [comment]
Pull request: https://github.com/terraref/traitvis-webapp/pull/27
