### ISSUE TITLE
Get all vignette code to work

### ISSUE THREAD

**Issue by KristinaRiemer** [terraref/tutorials#164]
Needs to be done by demo June 25

**Comment by KristinaRiemer** [comment]
Kimberly is working on the trait and weather vignettes, Kristina is working on images and synthesis vignettes.

**Comment by kimberlyh66** [comment]
@dlebauer can you change the access level of some canopy_height data for season 6 to be public?

**Comment by dlebauer** [comment]
I've made a subset of canopy_height and canopy_cover data public from Season 6 and some canopy_height data public from season 4. The subset is (season 4 or season 6) and (range 20 or range 30) with variants of the following sql code:

```sql
begin; 
update traits set access_level = 4 
where variable_id in 
(select id from variables where name in ('canopy_height', 'canopy_cover')) and 
site_id in (select id from sites where (sitename like '%Season 4%Range 20%') OR sitename like '%Season 4%Range 30%');
commit;
```

**Comment by kimberlyh66** [comment]
Okay. Thanks!
