### ISSUE TITLE
Review updated methods

### ISSUE THREAD

**Issue by kimberlyh66** [terraref/tutorials#174]
Methods have been updated by Duke and Maria. 

* Review updated methods in [google doc](https://docs.google.com/spreadsheets/d/1Pk_k5zm1W7I1jhzKoxMSGBhrHAPBWZh5GF2PL2vWrfk/edit#gid=112857053).

* Update SQL statements

**Comment by kimberlyh66** [comment]
attaching text document containing updated sql statements

**Comment by dlebauer** [comment]
Fantastic, thank you so much for getting deep into the weeds on this and sorting it out! 

I've run the updates on the production database and put the queries here for reference: https://gist.github.com/dlebauer/6e3e1152ea551b367a106ba800730e3c
