### ISSUE TITLE
Revise Name and Data Source for Weather Data in Stream and Tutorial

### ISSUE THREAD

**Issue by jdemieville-ua** [terraref/tutorials#176]
Tutorials refer to AZMET stations. We have a weather station in the corner of the field that is distinct from AZMET. AZMET is elsewhere on the farm and is not maintained by our group. Are the geostreams for the meteorological data actually pulling AZMET data, or are they using the data we're providing with an incorrect name? The station we manage is in the southwest corner of the field. Stream 3211 is pointing to a location where no weather station exists.

Since AZMET doesn't push data more frequently than once per hour, it seems pretty likely that this is just a misnamed stream/documentation.

[https://terraref.github.io/tutorials/accessing-meteorological-data.html](https://terraref.github.io/tutorials/accessing-meteorological-data.html)

- [x] Max needs to rename this
- [x] Update tutorials

**Comment by max-zilla** [comment]
I have renamed the sensor. The weather data for this station is stream 46431, which has (5 min bins) designation, 3211 was the old unbinned datapoints so it's empty.

**Comment by max-zilla** [comment]
@dlebauer who should i assign to update tutorials?

**Comment by dlebauer** [comment]
Thanks! I'll assign to @KristinaRiemer

**Comment by Chris-Schnaufer** [comment]
Refer to David's notes on this topic

**Comment by KristinaRiemer** [comment]
@max-zilla are these the changes that need to be made to the tutorial "Chapter 8 Accessing meteorological data"? 

1. Remove the first row in the stream id table (for stream id 3211)
2. Provide a different name for the row for stream id of 46431 because it's not AZMET?

**Comment by max-zilla** [comment]
@KristinaRiemer sorry, missed this. yes 46431 and the name is now simply "Weather Observations (5 min bins)"

**Comment by KristinaRiemer** [comment]
See pull request for this in #219.

**Comment by KristinaRiemer** [comment]
@max-zilla does the PR linked in my last comment look good to you?

**Comment by max-zilla** [comment]
@KristinaRiemer for the bits relevant to this discussion, yeah I think so.
