### ISSUE TITLE
Create a tutorial for accessing meta data using pyClowder

### ISSUE THREAD

**Issue by dlebauer** [terraref/tutorials#18]
Write a tutorial. It should contain

1. Introduction to the dataset
2. Introduction to the pyClowder functionality
3. demonstration of use of pyClowder to query environmental data
   * For the year 2016, plot time series of temperature,  precipitation, and sunlight for each of the three met stations at UIUC Energy Farm. Each plot should have three time series (one from each weather station)
   * If these data aren't available by the time you've gotten started, start with the Environmental Logger and the Weather station at UA MAC

This should be written in R markdown using the python engine (see http://rmarkdown.rstudio.com/authoring_knitr_engines.html). To do this, we will probably need to add dependencies (python, pyClowder) to the RStudio docker image, or else create one more image (Rstudio + pyClowder). @harshagrawal28 what are the dependencies? @craig-willis can you help with this ... or is this something that can be configured through the front-end?

**Comment by max-zilla** [comment]
@dlebauer is this what you have Chris working on?

**Comment by dlebauer** [comment]
@max-zilla Nope ... Chris is working on https://github.com/terraref/computing-pipeline/issues/173. 

But if you could add a section https://github.com/terraref/tutorials/blob/master/sensors/01-meteorological-data.Rmd, you can add python code like:

```{python}
code here
```

... or just post it here and I will add it to the tutorial

**Comment by harshagrawal28** [comment]
I'm not sure if pyClowder can be used to get the datapoints uploaded to geostreams. @max-zilla does pyClowder have this functionality? Or the only way is to use the Clowder API (GET /api/geostreams/datapoints?stream_id= ")?

**Comment by max-zilla** [comment]
@harshagrawal28 I didn't add a pyclowder method to fetch datapoints, but it works like you expect:
```
datapoints_url = "http://terraref.ncsa.illinois.edu/clowder/api/geostreams/datapoints?stream_id=300&since=2016-10-10T13:50:29Z"
```
"since" and "until" can be used to specify start/finish range of time as well.

we can just use requests in python for that with something like:
```
import requests
r = requests.get(datapoints_url) # might need to set content-type to application/json in headers
r.json()
```

**Comment by Chris-Schnaufer** [comment]
Closing this due to new direction to transformers and CyVerse environment
