### ISSUE TITLE
Get the https://github.com/terraref/toolserver-dockerfiles/blob/master/rstudio/Dockerfile to build

### ISSUE THREAD

**Issue by Chris-Schnaufer** [terraref/tutorials#185]
Taken from #147

**Comment by Chris-Schnaufer** [comment]
The version in https://github.com/terraref/toolserver-dockerfiles/blob/updated-for-python3-only/rstudio/Dockerfile builds an image successfully

**Comment by dlebauer** [comment]
I submitted a PR and it looks like the rstudio image successfully built https://github.com/terraref/toolserver-dockerfiles/pull/17
