### ISSUE TITLE
submit a PR w/ content copy-pasted https://github.com/cyverse-vice/rstudio-geospatial/blob/master/terraref-3.4.2/Dockerfile

### ISSUE THREAD

**Issue by Chris-Schnaufer** [terraref/tutorials#186]
Step 2.
Split out from #147

**Comment by Chris-Schnaufer** [comment]
@tyson-swetnam You can use https://github.com/terraref/toolserver-dockerfiles/blob/updated-for-python3-only/rstudio/Dockerfile as the basis for the CyVerse build

**Comment by dlebauer** [comment]
Content from https://github.com/terraref/tutorials/issues/186#issuecomment-516163290 has been moved to https://github.com/cyverse-vice/rstudio-geospatial/blob/master/terraref-3.6.0/Dockerfile
