### ISSUE TITLE
Tutorial to introduce Plant CV data and software

### ISSUE THREAD

**Issue by dlebauer** [terraref/tutorials#2]
@rachelshekar commented on [Thu Jan 26 2017](https://github.com/terraref/documentation/issues/123)

### Overview 

(updated Feb 5 2017 by @dlebauer)

Write tutorial to introduce people to TERRA REF's plantCV dataset and pipeline

* PlantCV output in sample space https://terraref.ncsa.illinois.edu/clowder/datasets/589519294f0c0650d062913f?space=57e42cd44f0cff4b58dd3eea (this is in public sample space, you can add more). 

This should go in the terraref/tutorials repository.
 
### Completion Criteria

* [ ] a self-guided intro to the plantCV data and pipeline 
   * intro may point to this video https://youtu.be/dCNYEl3ld0s of all steps from setting up pipeline to uploading / processing data
   * link to documentation of setting up Clowder
* [ ] explore a plantCV dataset in the Clowder interface (@rachelshekar)
  * Users should watch this video about how to start with Clowder web interface starting from 2m31s: https://youtu.be/dCNYEl3ld0s?t=2m31s 
* [ ] @craig-willis perhaps write up instructions for using the the plantCV docker image terraref/computing-pipeline#244 from within ndslabs. Please download the sample dataset and put it in a folder path that replicates the one on Roger.
* [ ] demonstrate how to explore the sample dataset from within iPython and / or Rmd notebook (@nfahlgren)
   * cross reference extracting associated traits from BETYdb via url-API, e.g.
        * https://terraref.ncsa.illinois.edu/bety/api/beta/cultivars?name=<GENOTYPENAME>&key=9999999999999999999999999999999999999999
        * see also / cross reference https://github.com/terraref/tutorials/blob/master/traits/02-danforth-phenotyping-facility.Rmd
* [ ] (further reading, i.e. links): how the plantCV pipeline can be adopted by other groups (@yanliu-chn) 
   * video shows how to set up Clowder+PlantCV cloud system https://youtu.be/dCNYEl3ld0s
   * is there a tutorial or documentation for running the plantCV pipeline somewhere? Linking to this is sufficient

---

@nfahlgren commented on [Tue Jan 31 2017](https://github.com/terraref/documentation/issues/123#issuecomment-276470753)

Would this work? http://plantcv.readthedocs.io/en/latest/. We have multiple tutorials in our documentation. Or something more TERRA-REF specific?

---

@dlebauer commented on [Tue Jan 31 2017](https://github.com/terraref/documentation/issues/123#issuecomment-276476518)

It would be great to have something that uses terraref data for tutorials.

**Comment by rachelshekar** [comment]
@dlebauer - do you want me to email the participants to ask them to watch the video before the workshop or just have it available at the start of the workshop on the notes doc? https://docs.google.com/document/d/1LhfO5HvItV6woWO6RyS77kQshPGJwBzAdq3SaByhXQY/edit

**Comment by dlebauer** [comment]
@rachelshekar no we can watch it together in real time. Maybe in two parts - That will make it easier to provide context.

**Comment by nfahlgren** [comment]
@dlebauer is the tutorial covering people who can log into Clowder and launch toolserver instances or people connecting to the data through the API?

**Comment by dlebauer** [comment]
>  is the tutorial covering people who can log into Clowder 

there should be public datasets in the Sample data space

> launch toolserver instances 

At least using a tool server where the machine has sample data - in the case of a workshop, we can't support > 10 tools launched from within Clowder now so we are using a separate platform to provide these tools.
 
> or people connecting to the data through the API?

Yes, the core bit would be 'here is how you get the data in clowder, here is how you get it via the API, and here is where you can get it in globus'.

**Comment by rachelshekar** [comment]
@dlebauer These links are compiled for the workshop participants at https://docs.google.com/document/d/1LhfO5HvItV6woWO6RyS77kQshPGJwBzAdq3SaByhXQY/edit?usp=sharing

**Comment by Chris-Schnaufer** [comment]
Closing as out of date. PlantCV has good documentation
