### ISSUE TITLE
Create document summarizing video walkthrough surveys

### ISSUE THREAD

**Issue by KristinaRiemer** [terraref/tutorials#212]

**Comment by KristinaRiemer** [comment]
The first complete version of this is here in this private repo: https://github.com/KristinaRiemer/terraref-videos 

I don't know if you want to review this @dlebauer, or if someone else would be suitable?

**Comment by Chris-Schnaufer** [comment]
Needs review

**Comment by KristinaRiemer** [comment]
@dlebauer we've gone through a few iterations of this report for the TERRA REF video tutorials, have you turned this in?

**Comment by dlebauer** [comment]
I think it is ready to submit but I can't find it at the link above https://github.com/KristinaRiemer/terraref-videos

**Comment by KristinaRiemer** [comment]
I put it in a private repo to make sure people's data weren't freely available, so I just added you as a collaborator. Here is a copy, and I also sent it to you on Slack. 
[MWBDH_minigrant_summary.pdf](https://github.com/terraref/tutorials/files/3755565/MWBDH_minigrant_summary.pdf)

**Comment by KristinaRiemer** [comment]
This was submitted via email on October 24.
