### ISSUE TITLE
Add instructions for using VICE to tutorials

### ISSUE THREAD

**Issue by dlebauer** [terraref/tutorials#220]

**Comment by KristinaRiemer** [comment]
Instructions for setting up and running Vice are currently in the notes for the first TERRA REF walkthrough (https://github.com/terraref/tutorials/blob/master/videos/first_walkthrough.Rmd, lines 29-49). Should they also go on the tutorials website in [Chapter 2](https://terraref.github.io/tutorials/vignettes-introduction.html#prerequisites) as the first section under **Prerequisites**?

**Comment by dlebauer** [comment]
Yes, and
* Ch 2 pre-requisites can be moved to the pre-requisites section under Ch 1
* also, the README has instructions for gettings started using workbench; we should move any useful 'getting started' information from the README into the tutorials themselves, and then link from the README to the tutorials. 
   * references to workbench in the readme, the tutorials, and the /workbench folder should be removed

**Comment by KristinaRiemer** [comment]
@dlebauer this is even further out of scope, but we should also talk about how to incorporate the walkthrough notes into the tutorials website (beyond adding the Vice app instructions).

**Comment by KristinaRiemer** [comment]
Closing this issue, review still needs to be finished, see [this followup issue](https://github.com/az-digitalag/organization/issues/124).
