### ISSUE TITLE
Implement Jupyter Notebook transformer enviroment in Cyverse DE

### ISSUE THREAD

**Issue by Sithyphus** [terraref/tutorials#233]
Take this docker container
https://github.com/Sithyphus/jupyter-transformer-sandbox/tree/develop
and make it available on Cyverse DE as an app

**Comment by MagicMilly** [comment]
I got this error message when trying to launch the app: 

`Message: "The app you are trying to use references one or more input files that you cannot access. Please contact the app integrator."`

**Comment by Sithyphus** [comment]
There's a small set of notes Milly had taken for us all during our meeting with Tyson for making a DE app
https://github.com/az-digitalag/organization/blob/de-vice-apps-notes/meeting-notes/2020-01-15_deploying-vice-apps.md
The app is in the DE environment. I haven't made it public yet but I'm working in another ticket to set up our organization's cyverse de community so we can share apps and the like without having to make them public.
