### ISSUE TITLE
Debugg ua-gantry-enviroment test-image travis/docker integration

### ISSUE THREAD

**Issue by Sithyphus** [terraref/tutorials#236]
Fix travis and docker testing. Building images aren't properly running tests and dependencies built within the test image seem to be missing or failing. Figure out why test image isn't testing properly in the travis environment.

**Comment by Sithyphus** [comment]
Finally after long hours of toiling away and countless travis builds the image and tests are working as intended in the travis environment. This is pretty great since now it should be  a simple matter to replicate this for any future transformers to make testing easier. Code of finalized image is here
https://github.com/AgPipeline/ua-gantry-environment/tree/test-development

**Comment by dlebauer** [comment]
woo hooo!
