### ISSUE TITLE
Change website in first walkthrough notes

### ISSUE THREAD

**Issue by KristinaRiemer** [terraref/tutorials#237]
The current URL under the **Video 5** section of the [first webinar walkthrough notes](https://github.com/terraref/tutorials/blob/master/videos/first_walkthrough.md) should be the TERRA REF-specific BetyDB: https://terraref.ncsa.illinois.edu/bety/

**Comment by dlebauer** [comment]
Will be fixed by #242 

Is the site being rebuilt properly?
