### ISSUE TITLE
Write a simplified guide to making a Cyverse DE App

### ISSUE THREAD

**Issue by Sithyphus** [terraref/tutorials#238]
Probably during writing hour, make a quick guide for making DE Apps and some issues that may arise in the process. Also update the OSF site with this information for the future.

**Comment by Sithyphus** [comment]
It's linked on the OSF site under Cyverse in computing resources.
That will link to here
https://github.com/az-digitalag/organization/blob/master/meeting-notes/2020-01-15_deploying-vice-apps.md

**Comment by MagicMilly** [comment]
Added to group [OSF Page](https://osf.io/tzmhp/wiki/Software%20and%20Computing%20Resources/)
