### ISSUE TITLE
"Exit"/"Offboarding" Protocols

### ISSUE THREAD

**Issue by Sithyphus** [terraref/tutorials#239]
Get with Chris and go over what needs to be done/taken care of in the last sprint before leaving.

**Comment by KristinaRiemer** [comment]
What do you mean by leaving? Is this something specific to the tutorials?

**Comment by Sithyphus** [comment]
This sprint should be my last sprint working here so David wanted me to talk with Chris over what's needed on my way out.

**Comment by KristinaRiemer** [comment]
I started and added some content to an offboarding page on the OSF: https://osf.io/tzmhp/wiki/Offboarding/

Also, this issue should maybe be closed and a new one opened up in the group org repo?

**Comment by Sithyphus** [comment]
Yes you're right, I'll do this right now.
