### ISSUE TITLE
Fill in README for canopy cover transformer

### ISSUE THREAD

**Issue by jvanderleeuw** [terraref/tutorials#243]
The README for the instructions for building, testing, and deploying the canopy cover transformer should be filled in

**Comment by KristinaRiemer** [comment]
Is this issue in the right place? This repo is for the [TERRA REF tutorials website](https://terraref.github.io/tutorials/), is the README going on this website or somewhere in [the pipeline organization](https://github.com/agPipeline)?

**Comment by dlebauer** [comment]
This is really a duplicate of or should be an issue within https://github.com/AgPipeline/issues-and-projects/issues/90
