### ISSUE TITLE
Create sample data repository folder in GitHub

### ISSUE THREAD

**Issue by Chris-Schnaufer** [terraref/tutorials#52]
This is where we will put code used to curate sample data and vignettes that illustrate how to use them.

# Imaging Sensors

Stereo-VIS
SWIR 
VNIR 
FLIR 
PS2 
3-D Scanner

# Non-imaging sensors

Reflectance sensor
Reflectance sensor 
Spectral reflectance
PAR sensor

Ocean Optics spectrometer
Clima weather instruments
CO2 Sensor

# Phenotypes

- provide csv w/ manual measurements 

# Genotypes

- add relevant VCF file

**Comment by dlebauer** [comment]
Created in github.com/terraref/sample-data
