### ISSUE TITLE
Improve vignettes by dropping API key

### ISSUE THREAD

**Issue by Chris-Schnaufer** [terraref/tutorials#55]
Improve vignettes after first cut

**Comment by dlebauer** [comment]
Vignettes should drop all mention of using API keys; there are public data in bety6 and public data on clowder https://terraref.ncsa.illinois.edu/clowder/spaces/5c50512a4f0c436195b9ad67, which doesn't require an apikey

**Comment by Chris-Schnaufer** [comment]
The images vignette runs without an API key but will not produce a result. We need to keep the discussion of an API key so that readers can query their own data
