### ISSUE TITLE
Create synthesis vignette

### ISSUE THREAD

**Issue by kimberlyh66** [terraref/tutorials#76]
Objective: demonstrate how to combine all data shown in previous vignettes; merge sensor, manually collected, and environmental data

Explanation: 
* link plot level manually collected data to images
* summarize weather data to GDD
* understand differences in spatial and temporal resolution

Output:

1. table with date, genotype, sitename, GDD, canopy cover, image filepath on disk, url to dataset on clowder
2. present three images representing the first, second, and third quartile canopy cover values
2. figure showing date on x axis and number of datapoints / files on the y axis to illustrate differences in temporal frequency

**Comment by Chris-Schnaufer** [comment]
@dlebauer Update ticket with new/additional information
