### ISSUE TITLE
Reorganize bookdown book to include vignettes

### ISSUE THREAD

**Issue by kimberlyh66** [terraref/tutorials#77]
These should be organized to include vignettes and the tutorials that we 

1. Introduction
1. Quick-start season 6 canopy cover data example
   - traits
   - weather
   - images
   - combining the data
2. Tutorials
   - traits
   - weather 
   - images

**Comment by KristinaRiemer** [comment]
So in terms of the naming system for the .Rmds that will make up this bookdown book, does this seem okay to everyone? 

00-introduction.Rmd
01-get-trait-data-R.Rmd
02-get-weather-data-R.Rmd
03-get-images-python.Rmd
04-synthesize-data.Rmd

@kimberlyh66 @Chris-Schnaufer @dlebauer

**Comment by Chris-Schnaufer** [comment]
Yes it does

**Comment by kimberlyh66** [comment]
Yes, looks good
