### ISSUE TITLE
Update rstudio docker container to support image analysis vignette

### ISSUE THREAD

**Issue by dlebauer** [terraref/tutorials#80]
- need to add python, terrautils
- update on workbench and DE

Update the [terraref geospatial dockerfile](https://github.com/terraref/toolserver-dockerfiles/blob/master/geospatial/Dockerfile) based on terrautils requirements + python in the [Cloud 9 dockerfile](https://github.com/terraref/toolserver-dockerfiles/blob/master/cloud9/Dockerfile)

This is completed when:
- The docker container is updated
- Can run all chunks in tutorial books

**Comment by Chris-Schnaufer** [comment]
Link to pull request: https://github.com/terraref/toolserver-dockerfiles/pull/15

**Comment by dlebauer** [comment]
Remaining tasks:
1. test that it works
2. merge & build on dockerhub
3. as Tyson to update image used on VICE

**Comment by Chris-Schnaufer** [comment]
Building container from https://github.com/terraref/toolserver-dockerfiles/blob/master/rstudio/Dockerfile

**Comment by Chris-Schnaufer** [comment]
Remaining tasks:

- [ ] Merge branches into master (top branch is updated-for-python3-only)
- [ ] Make official build onto dockerhub: terraref/rstudio-terraref:latest and terraref/rstudio-terraref:2.0
- [ ] Item 3. from dlbauer comment above (place instance on VICE)

**Comment by dlebauer** [comment]
Closing this and creating a new issue https://github.com/terraref/tutorials/issues/147
