### ISSUE TITLE
Create automated build and tests for tutorials book

### ISSUE THREAD

**Issue by dlebauer** [terraref/tutorials#82]
Similar to how PEcAn (github.com/pecanproject/pecan) uses Travis CI to 
- run tests (e.g. at a minimum the book should compile successfully to html) for any PR that is submitted
- build and publish book after changes are merged to master

**Comment by KristinaRiemer** [comment]
Oooh, I'm interested in taking this on!

**Comment by dlebauer** [comment]
Implemented by PR https://github.com/terraref/tutorials/pull/132
