### ISSUE TITLE
Debug traitvis-webapp

### ISSUE THREAD

**Issue by dlebauer** [terraref/tutorials#88]
Currently the webapp has the following issues

1. the 'live version' is not updating with new data
2. with the updated data, the application is missing figures, maps, and variable / cultivar selection buttons 

This is the live version

![image](https://user-images.githubusercontent.com/464871/51871013-70c73e00-2312-11e9-8b38-d5136e2b239b.png)

This is what happens when it is run with updated data:

![image](https://user-images.githubusercontent.com/464871/51871104-ad933500-2312-11e9-927b-e73cea020e34.png)

**Comment by dlebauer** [comment]
* still need to 
  * fix season 5 data and add it back to the full_cache_data
  *  get cron working again (in docker / bash rather than from w/in R)

**Comment by kimberlyh66** [comment]
@dlebauer To get the app working again, either `Season 5: Winter Wheat` or `Season 3: Winter Wheat` experiment name needs to be modified. Some output ids refer to the sub experiment names (ex.`Winter Wheat`), which stops the app from working in these cases since the ids are not unique.

**Comment by dlebauer** [comment]
@kimberlyh66 I could change these names but am afraid that the error could pop up again ... could you change code so that it can handle these duplicates? It is not clear why these names must be unique ...

One fix would be to use the full experiment name to index (e.g. in for loops) and only split the string and present the second half when creating the experiment and sub experiment labels? The database requires that the full experiment name be unique, so the error won't occur if the full experiment name is used for indexing  and subsetting. But ... 

... if there are a lot of bits of code to touch this could be a challenge; if it is much easier (hours instead of days) to use a less elegant fix, consider something such as 1) add an increasing number of whitespaces for duplicates (`Winter Wheat`, `Winter Wheat `, `Winter Wheat  ` or 2) appending an integer (e.g. `Winter Wheat 1`, `Winter Wheat 2`, `Winter Wheat 3`).

**Comment by kimberlyh66** [comment]
@dlebauer I think lines of code like this are breaking the app when sub experiment names are repeated: 

`output[[ paste0('variable_select_', subexp_name) ]] <- renderUI({
    selectInput(paste0('selected_variable_', subexp_name), 'Variable', variable_names)
  })`. 

Do you think we could fix the app by adding in the experiment name as well (to both the output and input ids)?  This will ensure that all input and output ids in the app are unique.

`output[[ paste0('variable_select_', exp_name, '_', subexp_name) ]] <- renderUI({
    selectInput(paste0('selected_variable_', exp_name, '_', subexp_name), 'Variable', variable_names)
  })`.
