### ISSUE TITLE
Add an introductions to Vignettes/Tutorials

### ISSUE THREAD

**Issue by Chris-Schnaufer** [terraref/tutorials#99]
- [x] Add introduction to Vignettes
- [x] Determine if introduction to tutorials is needed/needs-changes

**Comment by dlebauer** [comment]
It is not clear what content is needed beyond what is currently in index.Rmd?

**Comment by dlebauer** [comment]
need to flush out content for https://terraref.github.io/tutorials/vignettes-introduction.html

**Comment by dlebauer** [comment]
will be resolved by #150
